name: baseballboy_ver2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.1

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.3.1
  flutter_email_sender: ^5.2.0
  firebase_dynamic_links: ^5.0.12
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "assets/icons/icon.png"
  ios: true
  android: true
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/baseball_ground_illustration.jpeg
    - assets/images/野球場イラスト1.png
    - assets/images/野球場イラスト2.jpeg
    - assets/icons/yakyukozo_logo.png
